### ISSUE TITLE
Added NodeJS 8 support

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/mbtiles-offline#3]
Automated the process to build the `sqlite3` binaries and I've added NodeJS 8 support to [`sqlite3-offline`](https://github.com/DenisCarriere/sqlite3-offline) which is now updated in `mbtiles-offline`.

CC: @aaronlidman

**Comment by Fil** [comment]
seems like node 9 has broken this

```
/Users/fil/Source/electron-quick-start/node_modules/sqlite3-offline/binaries/index.js:21 Uncaught Error: NodeJS 8.9.3 Module 57 not compatible
    at Object.<anonymous> (/Users/fil/Source/electron-quick-start/node_modules/sqlite3-offline/binaries/index.js:21:9)
    at Object.<anonymous> (/Users/fil/Source/electron-quick-start/node_modules/sqlite3-offline/binaries/index.js:24:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/fil/Source/electron-quick-start/node_modules/sqlite3-offline/index.js:4:42)
```
